management.endpoints.web.exposure.include: '*'
management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  observations:
    annotations:
      enabled: true

# https://github.com/spring-projects/spring-boot/issues/39600
micrometer:
  observations:
    annotations:
      enabled: true

logbook:
  predicate:
    exclude:
      - path: /actuator/**
  strategy: body-only-if-status-at-least
  minimum-status: 400
  attribute-extractors:
    - type: JwtFirstMatchingClaimExtractor
      claim-names: [ "sub", "subject" ]
      claim-key: Principal
    - type: JwtAllMatchingClaimsExtractor
      claim-names: [ "sub", "iat" ]