apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true
  jsonData:
    httpMethod: POST
    exemplarTraceIdDestinations:
      # Field with internal link pointing to data source in Grafana.
      # datasourceUid value can be anything, but it should be unique across all defined data source uids.
      - datasourceUid: tempo
        name: trace_id

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    tracesToMetrics:
      datasourceUid: 'Prometheus'
      tags: [{ key: 'uri' }, { key: 'status' }]
      queries:
        - name: 'http requests'
          query: 'sum by(uri, status) (rate(http_server_requests_seconds_bucket{$$__tags}[$$__rate_interval]))'
    tracesToLogsV2:
      datasourceUid: 'Loki'
      tags: []
      mappedTags: []
      mapTagNamesEnabled: false
      spanStartTimeShift: 0
      spanEndTimeShift: 0
      filterByTraceID: false
      filterBySpanID: false
      lokiSearch: true
      # annoyingly this isn't in the documentation as of yet so had to get the config options out of some github issues
      # also, the linked start and end timeshift ranges don't seem to work correctly so I set them to zero
      # (where -/+10 min might make more sense
      customQuery: true
      query: '{job=~".+log"} | json | traceId="$${__span.traceId}"'
    serviceMap:
      datasourceUid: 'Prometheus'
    search:
      hide: false
    nodeGraph:
      enabled: true
- name: Loki
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: '"traceId":"(\w+)"'
        name: TraceID
        url: $${__value.raw}