global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: petclinic
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
    - targets:
      - host.docker.internal:8080
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]