management:
  endpoint:
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
  tracing:
    sampling:
      probability: 0.01

spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 2

server:
  tomcat:
#    threads:
#      max: 200
#    accept-count: 10
#    max-connections: 3000
    mbeanregistry:
      enabled: true
